.base-app-store:
  variables:
    DIR: app-store

  rules:
    - if: '$FORCE_PIPELINE =~ /ALL/ || $FORCE_PIPELINE =~ /app-store/'
    - if: '$CI_COMMIT_BEFORE_SHA == $_BANNED_RUN_ALL_SHA'
      when: never
    - if: '"$CI_COMMIT_REF_NAME" != "master" && "$CI_COMMIT_REF_NAME" != "dev" && "$CI_COMMIT_REF_NAME" != "new-ui"'
      when: never
    - changes:
      - ${DIR}/**/*


app-store:git-mirror:
  needs: []

  variables:
    MIRROR_REPOSITORY_NAME: app-store
    MIRROR_TRIGGER_REPO_VAR: hanaboso-pipes-php-app-store

  extends:
    - .base-git-mirror
    - .base-app-store
