version: '3.5'
services:
    app:
        image: hanabosocom/php-dev:php-8.1-alpine
        user: ${DEV_UID}:${DEV_GID}
        ports:
            - ${DEV_IP}:80:80
        working_dir: /var/www/pipes/app-store
        volumes:
            - ../:/var/www/pipes:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - KERNEL_CLASS=HbPFAppStoreTests\app\Kernel
            - COMPOSER_HOME=${HOME}/dev/.composer
            - PHP_WEBROOT=/var/www/pipes/app-store/tests/app/public
            - METRICS_SERVICE=mongo

    mongo:
        image: mongo:latest
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongo:/data/db

    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - ${DEV_IP}:8080:8080
        volumes:
            - ./openapi.yaml:/api.yaml
        environment:
            SWAGGER_JSON: /api.yaml

volumes:
    mongo: {}
