services:
    _defaults:
        public: '%public.services%'

    Hanaboso\HbPFAppStore\Controller\ApplicationController:
        class: Hanaboso\HbPFAppStore\Controller\ApplicationController
        arguments:
            - '@hbpf._application.handler.application'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    Hanaboso\HbPFAppStore\Controller\WebhookController:
        class: Hanaboso\HbPFAppStore\Controller\WebhookController
        arguments:
            - '@hbpf._application.handler.webhook'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]